### ISSUE TITLE
Andrew's Test

### ISSUE THREAD

**Issue by mcmahoad** [18F/hourofcode#71]
# Andrew's Test Markdown

List of Things
1. First thing
2. Seond thing

Link to thing (http://github.com)

**Comment by wslack** [comment]
Hey Andrew, you messed up the link but otherwise good! It should say "[Link to thing" then the parenthesis

**Comment by mcmahoad** [comment]
Thanks Will, where does it go from here? I made a mistake, you corrected, is there then a way for me to fix my issue or would I start I new one?

**Comment by wslack** [comment]
You can edit your issue by clicking the little pencil in the top right to try to fix it. Or you can post a new comment and try to get the markdown right there!

It otherwise looks like the [other exercises](https://pages.18f.gov/slides/github-basics/#/15) went ok for you? I think you are all set to edit any files you need to in 18F repos or get involved in relevant issues!

Please LMK of questions (I rejiggered a lot for this training). I am sure we can also give you rights to make your own branches in various repos if wanted; that's a little cleaner than forking if you want others to make edits on your branches.

**Comment by mcmahoad** [comment]
Thanks Will, I'll tinker a little tomorrow.

Training was great, you're a natural teacher.

Noah set me up a couple weeks back, so I have full rights within 18Fs
repos.

Sent from my iPhone

On Sep 15, 2015, at 6:36 PM, Will Slack notifications@github.com wrote:

You can edit your issue by clicking the little pencil in the top right to
try to fix it. Or you can post a new comment and try to get the markdown
right there!

It otherwise looks like the other exercises
https://pages.18f.gov/slides/github-basics/#/15 went ok for you? I think
you are all set to edit any files you need to in 18F repos or get involved
in relevant issues!

Please LMK of questions (I rejiggered a lot for this training). I am sure
we can also give you rights to make your own branches in various repos if
wanted; that's a little cleaner than forking if you want others to make
edits on your branches.

**Comment by NoelNS** [comment]
issues! i'm not sure that I'm in the right rp but I'm excited that I found this page!

**Comment by wslack** [comment]
@NoelNS this is a very old issue - you can add a comment here but would usually start a new issue yourself instead of commenting on an old one
